version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/nestmatch?sslmode=disable
      - NODE_ENV=development
      - PGHOST=db
      - PGPORT=5432
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGDATABASE=nestmatch
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=nestmatch
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    depends_on:
      - app

  grafana:
    image: grafana/grafana
    ports:
      - "3001:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

  # sonarqube:
  #   image: sonarqube:community
  #   ports:
  #     - "9000:9000"
  #   environment:
  #     - SONAR_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
  #     - SONAR_JDBC_USERNAME=postgres
  #     - SONAR_JDBC_PASSWORD=password
  #   volumes:
  #     - sonarqube_data:/opt/sonarqube/data
  #     - sonarqube_extensions:/opt/sonarqube/extensions
  #     - sonarqube_logs:/opt/sonarqube/logs
  #   depends_on:
  #     - db

volumes:
  postgres_data:
  grafana_data:
  # sonarqube_data:
  # sonarqube_extensions:
  # sonarqube_logs:
